
post http://localhost:8000/nursing
Content-Type: application/json

{
  "studentId": "B191112",
  "pulseRate": "adsf",
  "bloodPressure": "adfasdf",
  "spo2": "asdf",
  "temperature": "dfdf",
  "weight": "asf",
  "ecg": "adf"
}