get http://localhost:8000/medical-history
Content-Type: application/json

{
  "userId": "B191112",
  "appointmentDate": "2020-01-01",
  "reason": "fever",
  "sufferingFrom": "2024-01-01",
  "status": "pending"
}


###

get http://localhost:8000/medicines

###

get http://localhost:8000/admin